<a href="https://colab.research.google.com/github/tatbcc/data-science-bootcamp7/blob/main/R_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
library(tidyverse)
library(rvest)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.4.2     ✔ purrr   1.0.1
✔ tibble  3.2.1     ✔ dplyr   1.1.1
✔ tidyr   1.3.0     ✔ stringr 1.4.1
✔ readr   2.1.4     ✔ forcats 1.0.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


Attaching package: ‘rvest’


The following object is masked from ‘package:readr’:

    guess_encoding

In [ ]:
url <- "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

movie_name <- url %>%
  read_html() %>%
  html_elements("h3.lister-item-header") %>%
  html_text2()

ratings <- url %>%
  read_html() %>%
  html_elements("div.ratings-imdb-rating") %>%
  html_text2() %>%
  as.numeric()

vote <- url %>%
  read_html() %>%
  html_elements("p.sort-num_votes-visible") %>%
  html_text2() 

df <- data.frame(movie_name,ratings,vote)

In [ ]:
# create new df with split vote
new_df <- df %>% 
  separate(col = vote, sep =  "\\|", 
          into=c("Vote","Gross","Rank"))
#check NA
new_df %>%
  is.na() %>%
  colSums()
#locate NA row
na_row <- which(is.na(new_df$Rank))
#move data and fill NA
for (i in na_row){
  new_df[i,"Rank"] <- new_df[i,"Gross"]
  new_df[i,"Gross"] <- NA
}

Warning message:
“Expected 3 pieces. Missing pieces filled with `NA` in 3 rows [30, 31, 48].”

movie_name    ratings       Vote      Gross       Rank
         0          0          0          0          3

In [ ]:
genre <- url %>%
  read_html() %>%
  html_nodes("span.genre") %>%
  html_text2()

data.frame(new_df,genre)

   movie_name                                                   ratings
1  1. The Shawshank Redemption (1994)                           9.3
2  2. The Godfather (1972)                                      9.2
3  3. The Dark Knight (2008)                                    9.0
4  4. Schindler's List (1993)                                   9.0
5  5. The Lord of the Rings: The Return of the King (2003)      9.0
6  6. 12 Angry Men (1957)                                       9.0
7  7. The Godfather Part II (1974)                              9.0
8  8. Pulp Fiction (1994)                                       8.9
9  9. Inception (2010)                                          8.8
10 10. The Lord of the Rings: The Fellowship of the Ring (2001) 8.8
11 11. Fight Club (1999)                                        8.8
12 12. Forrest Gump (1994)                                      8.8
13 13. The Lord of the Rings: The Two Towers (2002)             8.8
14 14. The Good, the Bad and the Ugly (1966)                    8.8
15 15. Goodfellas (1990)                                        8.7
16 16. The Matrix (1999)                                        8.7
17 17. Star Wars: Episode V - The Empire Strikes Back (1980)    8.7
18 18. One Flew Over the Cuckoo's Nest (1975)                   8.7
19 19. Interstellar (2014)                                      8.6
20 20. Star Wars: Episode IV - A New Hope (1977)                8.6
21 21. Se7en (1995)                                             8.6
22 22. The Silence of the Lambs (1991)                          8.6
23 23. Saving Private Ryan (1998)                               8.6
24 24. The Green Mile (1999)                                    8.6
25 25. Spirited Away (2001)                                     8.6
26 26. City of God (2002)                                       8.6
27 27. Terminator 2: Judgment Day (1991)                        8.6
28 28. Life Is Beautiful (1997)                                 8.6
29 29. Seven Samurai (1954)                                     8.6
30 30. It's a Wonderful Life (1946)                             8.6
31 31. Harakiri (1962)                                          8.6
32 32. Gladiator (2000)                                         8.5
33 33. Parasite (2019)                                          8.5
34 34. Whiplash (2014)                                          8.5
35 35. Back to the Future (1985)                                8.5
36 36. The Departed (2006)                                      8.5
37 37. Léon: The Professional (1994)                            8.5
38 38. Alien (1979)                                             8.5
39 39. The Prestige (2006)                                      8.5
40 40. The Lion King (1994)                                     8.5
41 41. The Pianist (2002)                                       8.5
42 42. The Usual Suspects (1995)                                8.5
43 43. Psycho (1960)                                            8.5
44 44. American History X (1998)                                8.5
45 45. The Intouchables (2011)                                  8.5
46 46. Casablanca (1942)                                        8.5
47 47. Once Upon a Time in the West (1968)                      8.5
48 48. Grave of the Fireflies (1988)                            8.5
49 49. Cinema Paradiso (1988)                                   8.5
50 50. Rear Window (1954)                                       8.5
   Vote              Gross             Rank
1  Votes: 2,737,257   Gross: $28.34M    Top 250: #1
2  Votes: 1,903,506   Gross: $134.97M   Top 250: #2
3  Votes: 2,710,342   Gross: $534.86M   Top 250: #3
4  Votes: 1,381,705   Gross: $96.90M    Top 250: #6
5  Votes: 1,882,439   Gross: $377.85M   Top 250: #7
6  Votes: 810,133     Gross: $4.36M     Top 250: #5
7  Votes: 1,297,463   Gross: $57.30M    Top 250: #4
8  Votes: 2,103,494   Gross: $107.93M   Top 250: #8
9  Votes: 2,405,946   Gross: $292.58M   Top 250: #14
10 Votes: 1,911,239   Gross: $315.54M   Top 250: #9
11 Votes: 2,179,523   Gross: $37.03M    Top 250: #12
12 Votes: 2,130,055   Gross: $330.25M   Top 250: #11
13 Votes: 1,699,273   Gross: $342.55M   Top 250: #13
14 Votes: 775,411     Gross: $6.10M     Top 250: #10
15 Votes: 1,188,043   Gross: $46.84M    Top 250: #17
16 Votes: 1,952,608   Gross: $171.48M   Top 250: #16
17 Votes: 1,317,691   Gross: $290.48M   Top 250: #15
18 Votes: 1,026,349   Gross: $112.00M   Top 250: #18
19 Votes: 1,901,288   Gross: $188.02M   Top 250: #25
20 Votes: 1,390,186   Gross: $322.74M   Top 250: #28
21 Votes: 1,692,365   Gross: $100.13M   Top 250: #19
22 Votes: 1,463,591   Gross: $130.74M   Top 250: #22
23 Votes: 1,419,780   Gross: $216.54M   Top 250: #23
24 Votes: 1,331,107   Gross: $136.80M   Top 250: #27
25 Votes: 786,734     Gross: $10.06M    Top 250: #31
26 Votes: 769,233     Gross: $7.56M     Top 250: #24
27 Votes: 1,120,389   Gross: $204.84M   Top 250: #29
28 Votes: 709,454     Gross: $57.60M    Top 250: #26
29 Votes: 352,035     Gross: $0.27M     Top 250: #21
30 Votes: 471,095    NA                 Top 250: #20
31 Votes: 60,608     NA                 Top 250: #45
32 Votes: 1,532,009   Gross: $187.71M   Top 250: #36
33 Votes: 849,358     Gross: $53.37M    Top 250: #34
34 Votes: 900,133     Gross: $13.09M    Top 250: #40
35 Votes: 1,234,701   Gross: $210.61M   Top 250: #30
36 Votes: 1,352,553   Gross: $132.38M   Top 250: #39
37 Votes: 1,185,952   Gross: $19.50M    Top 250: #35
38 Votes: 901,058     Gross: $78.90M    Top 250: #51
39 Votes: 1,360,889   Gross: $53.09M    Top 250: #41
40 Votes: 1,082,029   Gross: $422.78M   Top 250: #37
41 Votes: 853,273     Gross: $32.57M    Top 250: #32
42 Votes: 1,102,230   Gross: $23.34M    Top 250: #42
43 Votes: 685,865     Gross: $32.00M    Top 250: #33
44 Votes: 1,140,963   Gross: $6.72M     Top 250: #38
45 Votes: 879,152     Gross: $13.18M    Top 250: #46
46 Votes: 582,221     Gross: $1.02M     Top 250: #43
47 Votes: 336,363     Gross: $5.32M     Top 250: #48
48 Votes: 286,251    NA                 Top 250: #44
49 Votes: 267,680     Gross: $11.99M    Top 250: #49
50 Votes: 500,834     Gross: $36.76M    Top 250: #50
   genre
1  Drama
2  Crime, Drama
3  Action, Crime, Drama
4  Biography, Drama, History
5  Action, Adventure, Drama
6  Crime, Drama
7  Crime, Drama
8  Crime, Drama
9  Action, Adventure, Sci-Fi
10 Action, Adventure, Drama
11 Drama
12 Drama, Romance
13 Action, Adventure, Drama
14 Adventure, Western
15 Biography, Crime, Drama
16 Action, Sci-Fi
17 Action, Adventure, Fantasy
18 Drama
19 Adventure, Drama, Sci-Fi
20 Action, Adventure, Fantasy
21 Crime, Drama, Mystery
22 Crime, Drama, Thriller
23 Drama, War
24 Crime, Drama, Fantasy
25 Animation, Adventure, Family
26 Crime, Drama
27 Action, Sci-Fi
28 Comedy, Drama, Romance
29 Action, Drama
30 Drama, Family, Fantasy
31 Action, Drama, Mystery
32 Action, Adventure, Drama
33 Drama, Thriller
34 Drama, Music
35 Adventure, Comedy, Sci-Fi
36 Crime, Drama, Thriller
37 Action, Crime, Drama
38 Horror, Sci-Fi
39 Drama, Mystery, Sci-Fi
40 Animation, Adventure, Drama
41 Biography, Drama, Music
42 Crime, Drama, Mystery
43 Horror, Mystery, Thriller
44 Crime, Drama
45 Biography, Comedy, Drama
46 Drama, Romance, War
47 Western
48 Animation, Drama, War
49 Drama, Romance
50 Mystery, Thriller

In [ ]:
url1 <- "https://ceoworld.biz/2021/06/20/the-worlds-best-countries-for-quality-of-life-2021/"

best_country <- url1 %>%
  read_html() %>%
  html_elements("td.column-2") %>%
  html_text2()

score <- url1 %>%
  read_html() %>%
  html_elements("td.column-3") %>%
  html_text2()

BestCounrty_2021 <- data.frame(best_country,score)

BestCounrty_2021 <- BestCounrty_2021 %>%
  rowid_to_column() %>%
  rename(Rank = rowid)

In [ ]:
BestCounrty_2021

    Rank best_country             score
1    1   Finland                  99.06
2    2   Denmark                  98.13
3    3   Norway                   96.75
4    4   Belgium                  96.53
5    5   Sweden                   96.15
6    6   Switzerland              94.4
7    7   Netherlands              93.69
8    8   France                   92.08
9    9   Germany                  91.26
10  10   Japan                    91.23
11  11   United Kingdom           90.68
12  12   Canada                   90.3
13  13   South Korea              89.67
14  14   United States            89.11
15  15   Taiwan                   88.73
16  16   Austria                  88.52
17  17   Australia                88.23
18  18   Ireland                  87.76
19  19   Singapore                87.64
20  20   Spain                    87.62
21  21   Italy                    86.85
22  22   Czech Republic           86.6
23  23   Portugal                 86.38
24  24   New Zealand              86.02
25  25   Luxembourg               85.08
26  26   Iceland                  84.96
27  27   Liechtenstein            84.75
28  28   Hong Kong                84.64
29  29   Israel                   84.43
30  30   United Arab Emirates     83.79
⋮   ⋮    ⋮                        ⋮
136 136  Kyrgyzstan               44.81
137 137  Somalia                  44.73
138 138  Eritrea                  43.95
139 139  Malawi                   42.25
140 140  Tajikistan               41.6
141 141  Togo                     40.95
142 142  Montenegro               38.56
143 143  Mauritania               38.08
144 144  Eswatini                 37.77
145 145  Guyana                   37.56
146 146  Sierra Leone             37.3
147 147  Suriname                 36.65
148 148  Burundi                  36.55
149 149  Timor Leste              36
150 150  Liberia                  35.61
151 151  South Sudan              35.52
152 152  Djibouti                 35.39
153 153  Central African Republic 35.13
154 154  Cape Verde               34.81
155 155  Belize                   34.78
156 156  Gambia                   34.74
157 157  Seychelles               34.74
158 158  San Marino               34.35
159 159  Guinea Bissau            34.32
160 160  Dominica                 34.19
161 161  Comoros                  33.14
162 162  North Korea              32.41
163 163  Montserrat               32.06
164 164  Sudan                    31.67
165 165  Syria                    31.55